spring:
  h2:
    console:
      enable: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:customerDB
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect