INSERT INTO CUSTOMERS (ID, NAME, CREATE_AT, MODIFIED_AT, DOCUMENT, BIRTH_DATE, ADDRESS) VALUES (1, 'GABRIEL',
 CURRENT_DATE, CURRENT_DATE , '757.971.640-27', SYSDATE, 'Rua A');
INSERT INTO CUSTOMERS (ID, NAME, CREATE_AT, MODIFIED_AT, DOCUMENT, BIRTH_DATE, ADDRESS) VALUES (2, 'JOSE',
 CURRENT_DATE, CURRENT_DATE , '470.610.260-06', SYSDATE, 'Rua B');
INSERT INTO CUSTOMERS (ID, NAME, CREATE_AT, MODIFIED_AT, DOCUMENT, BIRTH_DATE, ADDRESS) VALUES (3, 'MARCIA',
 CURRENT_DATE, CURRENT_DATE , '551.236.060-41', SYSDATE, 'Rua C');
INSERT INTO CUSTOMERS (ID, NAME, CREATE_AT, MODIFIED_AT, DOCUMENT, BIRTH_DATE, ADDRESS) VALUES (4, 'GABRIELA',
 CURRENT_DATE, CURRENT_DATE , '394.606.370-51', SYSDATE, 'Rua D');
 INSERT INTO CUSTOMERS (ID, NAME, CREATE_AT, MODIFIED_AT, DOCUMENT, BIRTH_DATE, ADDRESS) VALUES (5, 'GABRIELA',
  CURRENT_DATE, CURRENT_DATE , '625.901.300-07', SYSDATE, 'Rua D');

